config/routes.rb
Shortener::Application.routes.draw do

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: 'shorters#new'

  resources :shorters

  get '/user/my_links', to: 'user#my_links', as: "my_links"
  get '/user', to: 'user#index'

  match ":identifier" => "shorters#redirect", as: "short_link"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.id
      can :manage, Shorter, :user_id => user.id
      can :read, :all
    else
      can :read, :all
      can :create, Shorter
    end

  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  attr_accessible :name
  validates :name, presence: true, uniqueness: true

  has_many :users

  def self.get_admin_id
    role = self.find_by_name 'admin'
    if role
      return role.id
    end
    return -1
  end
end

app/models/shorter.rb
class Shorter < ActiveRecord::Base
  attr_accessible :description, :identifier, :url, :status, :user_id
  validates :identifier, :uniqueness => true
  validates :url, presence: true,
                  length: {minimum: 10}

  belongs_to :user

  #self.per_page = 10

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid
  # attr_accessible :title, :body

  belongs_to :role
  has_many :shorters
  devise :omniauthable


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20],
        )
      end    end
  end

  def admin?
    if self != nil?
      return self.role_id == Role.get_admin_id
    end
    return false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :ini_search

  def ini_search
    @q = Shorter.search(params[:q])
  end

  def after_sign_in_path_for(resource_or_scope)

    if session[:urls_shorted]
      Shorter.where(:id => session[:urls_shorted]).update_all(:user_id =>current_user.id)
    end
    super
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/shorters_controller.rb
class ShortersController < ApplicationController


  # GET /shorters
  # GET /shorters.json
  def index
    @shorters = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @shorters }
    end
  end

  # GET /shorters/1
  # GET /shorters/1.json
  def show
    @shorter = Shorter.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @shorter }
    end
  end

  # GET /shorters/new
  # GET /shorters/new.json
  def new
    @shorter = Shorter.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @shorter }
    end
  end

  # GET /shorters/1/edit
  def edit
    @shorter = Shorter.find(params[:id])
  end

  # POST /shorters
  # POST /shorters.json
  def create
    @shorter = Shorter.new(params[:shorter])

    unique_url = (Digest::MD5.hexdigest "#{SecureRandom.hex(2)}-#{DateTime.now.to_s}")

    @shorter.identifier = unique_url

    if user_signed_in?
      @shorter.user_id = current_user.id
    end

    respond_to do |format|
      if @shorter.save
        if !user_signed_in?
          (session[:urls_shorted] ||= []) << @shorter.id
        end
        format.html { redirect_to @shorter, notice: 'Shorter was successfully created.' }
        format.json { render :json => {message: "Created successfully", url: short_link_url(@shorter.identifier) } }
      else
        format.html { render action: "new" }
        format.json { render json: @shorter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shorters/1
  # PUT /shorters/1.json
  def update

    @shorter = Shorter.find(params[:id])

    authorize! :update, @shorter

    respond_to do |format|
      if @shorter.update_attributes(params[:shorter])
        format.html { redirect_to @shorter, notice: 'Shorter was successfully updated.'}
        format.json { render :json => {message: "Updated successfully", url: short_link_url(@shorter.identifier) } }
      else
        format.html { render action: "edit" }
        format.json { render :json => {message: "Updated failed", url: short_link_url(@shorter.identifier) } }
      end
    end
  end

  # DELETE /shorters/1
  # DELETE /shorters/1.json
  def destroy
    @shorter = Shorter.find(params[:id])

    authorize! :destroy, @shorter

    @shorter.destroy

    respond_to do |format|
      format.html { redirect_to shorters_url }
      format.json { head :no_content }
    end
  end

  def redirect
    @shorter = Shorter.find_by_identifier params[:identifier]
    if @shorter
      redirect_to @shorter.url
    end
  end

  def expire

  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :authenticate_user!

  def my_links
    @shorters = current_user.shorters
  end

  def index
    @shorters = current_user.shorters.paginate(:page => params[:page], :per_page => 10)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/shorters_helper.rb
module ShortersHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Shortener"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body

    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a{class: "btn btn-navbar", :data => {:target => ".nav-collapse", :toggle => "collapse"} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a{class: "brand", href: root_path } Shortener
          .container-fluid.nav-collapse
            %ul.nav
              %li= link_to "All links", shorters_path
              - if user_signed_in?
                %li= link_to "My links", my_links_path


            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to "Logout", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Register", new_user_registration_path
                %li= link_to "Login", user_session_path
                %li= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)




    .container-fluid
      .row-fluid
        .pull-right
          = search_form_for @q do |f|
            = f.text_field :url_cont
            = f.submit

        .span9
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2014

app/views/shorters/_form.html.haml
= form_for(@shorter, :remote => true, :html => {:'data-type' => 'json', :multipart => true})  do |f|
  - if @shorter.errors.any?
    #error_explanation
      %h2
        = pluralize(@shorter.errors.count, "error")
        prohibited this shorter from being saved:
      %ul
        - @shorter.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :url
    %br/
    = f.text_field :url, class: "form-control input-normal"
  .actions
    = f.submit

#new_url
  - if !@shorter.identifier.nil? && !@shorter.new_record?
    = link_to root_url+@shorter.identifier, root_url+@shorter.identifier, target: '_blank'
  - else
    = link_to "", root_url, target: '_blank'

app/views/shorters/edit.html.haml
.row
  .span8.offset6
    .center
      %h1 Editing shorter

      = render 'form'

      = link_to 'Show', @shorter

      = link_to 'Back', shorters_path

app/views/shorters/index.html.haml
%h1 Listing shorters

.col-13
  .row-fluid
    .span3 Url
    .span4 Identifier
    .span3 Description
    .span2 Actions

  - @shorters.each do |shorter|
    .row-fluid
      .span3= shorter.url
      .span4= link_to shorter.identifier, short_link_path(:identifier => shorter.identifier), target: '_blank'
      .span3= shorter.description
      .span2
        = link_to 'Show', shorter
        - if can? :manage_owners, shorter
          = link_to 'Edit', edit_shorter_path(shorter)
          = link_to 'Destroy', shorter, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = will_paginate @shorters

= link_to 'New Shorter', new_shorter_path

app/views/shorters/new.html.haml
.row
  .span8.offset6
    .center
      = render 'form'

      = link_to 'Back', shorters_path

app/views/shorters/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @shorter.url

%p
  %b Identifier:
  = @shorter.identifier


%b
  %b Description:
  = @shorter.description

%br

= link_to 'Edit', edit_shorter_path(@shorter)
= link_to 'Back', shorters_path

app/views/user/index.html.haml
%h1 Listing shorters

.col-13
  .row-fluid
    .span3 Url
    .span4 Identifier
    .span3 Description
    .span2 Actions

  - @shorters.each do |shorter|
    .row-fluid
      .span3= shorter.url
      .span4= link_to shorter.identifier, short_link_path(:identifier => shorter.identifier), target: '_blank'
      .span3= shorter.description
      .span2
        = link_to 'Show', shorter
        - if can? :manage_owners, shorter
          = link_to 'Edit', edit_shorter_path(shorter)
          = link_to 'Destroy', shorter, method: :delete, data: { confirm: 'Are you sure?' }

%br
  = will_paginate @shorters
= link_to 'New Shorter', new_shorter_path

app/views/user/my_links.html.haml
%h1 Listing shorters

.col-13
  .row-fluid
    .span3 Url
    .span4 Identifier
    .span3 Description
    .span2 Actions

  - @shorters.each do |shorter|
    .row-fluid
      .span3= shorter.url
      .span4= link_to shorter.identifier, short_link_path(:identifier => shorter.identifier), target: '_blank'
      .span3= shorter.description
      .span2
        = link_to 'Show', shorter
        = link_to 'Edit', edit_shorter_path(shorter)
        = link_to 'Destroy', shorter, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Shorter', new_shorter_path